#!/bin/sh
# Gradle wrapper script - this will be generated by Android Studio
# For GitHub Actions, we use the system gradle
if [ -f "./gradlew" ]; then
    exec ./gradlew "$@"
else
    gradle "$@"
fi
